name: Main workflow

# The event triggers are configured as following:
# - on any pull request, trigger the workflow
# This is to avoid running the workflow twice on pull requests.
on:
  pull_request:

jobs:
  build_lint_and_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Building packages
        run: pnpm build

      - name: Running static type checking
        run: pnpm typecheck

      - name: Running linters and tests
        run: pnpm jest --projects jest.{eslint,test}.config.js --reporters jest-silent-reporter
        env:
          CI: true
