name: express-request-correlator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        uses: Borales/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: Borales/actions-yarn@master
        with:
          args: lint
      - name: Test
        uses: Borales/actions-yarn@master
        with:
          args: test
      - name: Build
        uses: Borales/actions-yarn@master
        with:
          args: build
